services: 
    db:
      container_name: postgres_container
      image: postgis/postgis
      restart: always
      volumes:
        - ./data/db:/var/lib/postgtesql/data
      environment:
         POSTGRES_USER: postgis
         POSTGRES_PASSWORD: 1111
         POSTGRES_DB: master
      ports: 
        - 5433:5432
      networks:
         app_net:
            ipv4_address: 192.168.0.22

    pgadmin:
      user: root
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      volumes:
        - ./data/pgadmin-data:/var/lib/pgadmin
      environment:
         PGADMIN_DEFAULT_EMAIL: admin@admin.com
         PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - 5050:80
      networks:
         app_net:
            ipv4_address: 192.168.0.3

    queue:
      container_name: rabbitMq_container
      image: rabbitmq:3-management-alpine
      restart: unless-stopped
      volumes:
        - ./data/rabbitmq/data/:/var/lib/rabbitmq/
        - ./data/rabbitmq/log/:/var/log/rabbitmq
      ports: 
       - 5672:5672
       - 15672:15672
      networks:
         app_net:
            ipv4_address: 192.168.0.4

networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: "192.168.0.0/24"
                  gateway: 192.168.0.1  