services: 
    db:
      container_name: postgres_container
      image: postgres:latest
      restart: always
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: 1111
         POSTGRES_DB: master
      ports: 
        - 5432:5432
      networks:
         app_net:
            ipv4_address: 192.168.0.2

    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      volumes:
        - ./data/pgadmin-data:/var/lib/pgadmin
      environment:
         PGADMIN_DEFAULT_EMAIL: admin@admin.com
         PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - 5050:80
      networks:
         app_net:
            ipv4_address: 192.168.0.3

    queue: 
      image: rabbitmq:latest 
      ports: 
       - 5672:5672
      networks:
         app_net:
            ipv4_address: 192.168.0.4

networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: "192.168.0.0/24"
                  gateway: 192.168.0.1  